# Generated by Django 5.2 on 2025-05-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('entrance_exam', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='study_materials/')),
            ],
        ),
    ]
