# Generated by Django 5.2 on 2025-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
